name: Build and Publish B2PC
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        shell: bash
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/B2PC-Setup-${{ env.VERSION }}.exe
            out/make/B2PC-Setup-${{ env.VERSION }}.exe.blockmap
            out/make/latest.yml
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}